"""Group Table contacts rlshp removed

Revision ID: 5ebe4fb73bbd
Revises: ff53ae97942c
Create Date: 2024-01-11 11:01:05.801751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebe4fb73bbd'
down_revision = 'ff53ae97942c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
